# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Features Controller

# Model Form Field configuration
form: $/andocobo/projectfeatures/models/features/fields.yaml

# Model Class name
modelClass: andocobo\ProjectFeatures\Models\Feature

# Default redirect location
defaultRedirect: andocobo/projectfeatures/featurescontroller

# Create page
create:
    title: Create Project Feature
    redirect: andocobo/projectfeatures/featurescontroller
    redirectClose: andocobo/projectfeatures/featurescontroller
    flashSave: New project feature has been created!

# Update page
update:
    title: Edit Project Feature
    redirect: andocobo/projectfeatures/featurescontroller
    redirectClose: andocobo/projectfeatures/featurescontroller
    flashSave: Project feature has been edited!
    flashDelete: Project feature has been deleted!

# Preview page
preview:
    title: Preview Features Controller